export const PERSONS_ERROR = 'PERSONS_ERROR';
export const PERSONS_LOADING = 'PERSONS_LOADING';
export const PERSONS_FETCH_DATA_SUCCESS = 'PERSONS_FETCH_DATA_SUCCESS';
export const PERSONS_FILTERED = 'PERSONS_FILTERED';
